#!/bin/sh
### BEGIN INIT INFO
# Provides:          ipSendEmaild
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: ipSendEmaild
# Description:       Send email on IP change
### END INIT INFO
NAME=ipSendEmaild
DAEMON=$0
TIMEOUT=15s
TMPDIR=/run/${NAME}
CFGDIR=/etc/${NAME}
FROM=`cat ${CFGDIR}/from`
FROMUSER=`cat ${CFGDIR}/fromuser`
if [ -z "${FROMUSER}" ]; then
	FROMUSER=$FROM
fi
PASSWDFILE=$CFGDIR/passwd
TO=`cat $CFGDIR/to`
SERVER=`cat $CFGDIR/server`
OPTIONS="message-file=ip"
PIDFILE=/run/${NAME}.pid
do_prepare()
{
	true
}
do_loop()
{
	mkdir -pv ${TMPDIR}
	do_clean
	install -Dvm400 $PASSWDFILE "$TMPDIR/passwd"
	cd "$TMPDIR"
	#ip addr > ip.orig
	#grep -vwe valid_lft ip.orig > ip.orig.greped
	while true; do
		ip addr > ip
		grep -vwe valid_lft ip > ip.greped
		diff ip.greped ip.orig.greped
		if [ $? -ne 0 ]; then
			echo "==> IPADDR Differs, sending email"
			timeout "$TIMEOUT" sendEmail \
				-f "${FROM}" \
				-t "${TO}" \
				-u "IPADDR:`hostname`" \
				-o "${OPTIONS}" -v \
				-s "${SERVER}" \
				-xu "${FROMUSER}" \
				-xp < passwd
			export flag=$?
			if [ $flag -eq 0 ]; then
				echo "==> EMAIL SUCCESSFULLY SENT."
				cp ip ip.orig
				cp ip.greped ip.orig.greped
				sleep 60
			else	echo "==> SENDING UNSUCCESSFUL"
				sleep 30
			fi
		else 	echo "==> IPADDR unchanged, sleeping"
			sleep 30
		fi
	done
}
do_clean()
{
	if [ ! -z "${TMPDIR}" ]; then
		rm -vf ${TMPDIR}/passwd ${TMPDIR}/ip*
	fi
}
do_start()
{
	start-stop-daemon -bmS --pidfile ${PIDFILE} --exec ${DAEMON} -- loop
}
do_stop()
{
	start-stop-daemon --stop --pidfile ${PIDFILE} --exec ${DAEMON}
	${DAEMON} clean
}
case $1 in
prepare)
	do_prepare;;
start)
	do_start;;
stop)
	do_stop;;
restart)
	do_start&&do_stop;;
clean)
	do_clean;;
loop)
	do_loop;;
*)
	false;;
esac
